src/Entity/Mortgage.php
<?php

namespace App\Entity;

use App\Enum\MortgageAmortizationTypeEnum;
use App\Enum\MortgageBillingPeriodEnum;
use App\Enum\MortgageTypeEnum;
use App\Repository\MortgageRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;


#[ORM\Entity(repositoryClass: MortgageRepository::class)]
class Mortgage
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    #[Assert\NotNull]
    private ?\DateTimeImmutable $FromAt = null;

    #[ORM\Column(type: Types::DATE_IMMUTABLE)]
    #[Assert\NotNull]
    private ?\DateTimeImmutable $toAt = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: false)]
    private ?Bank $bank = null;

    #[ORM\ManyToOne(inversedBy: 'mortgages')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Property $property = null;

    #[ORM\Column(enumType: MortgageBillingPeriodEnum::class)]
    private ?MortgageBillingPeriodEnum $billingPeriod = null;

    #[ORM\Column(enumType: MortgageTypeEnum::class)]
    private ?MortgageTypeEnum $mortgageType = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 5, scale: 3)]
    private ?string $rate = null;

    /**
     * @var Collection<int, FinancialEntry>
     */
    #[ORM\OneToMany(targetEntity: FinancialEntry::class, mappedBy: 'mortgage')]
    private Collection $financialEntries;

    #[ORM\Column(type: Types::DECIMAL, precision: 10, scale: 2, nullable: true)]
    private ?string $amount = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 5, scale: 2, nullable: true)]
    private ?string $amortizationPercent = null;

    #[ORM\Column(nullable: true, enumType: MortgageAmortizationTypeEnum::class)]
    private ?MortgageAmortizationTypeEnum $amortizationType = null;

    #[ORM\Column(type: Types::DECIMAL, precision: 7, scale: 2, nullable: true)]
    private ?string $amortizationAmount = null;

    public function __construct()
    {
        $this->mortgagePayments = new ArrayCollection();
        $this->financialEntries = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFromAt(): ?\DateTimeImmutable
    {
        return $this->FromAt;
    }

    public function setFromAt(\DateTimeImmutable $FromAt): static
    {
        $this->FromAt = $FromAt;

        return $this;
    }

    public function getToAt(): ?\DateTimeImmutable
    {
        return $this->toAt;
    }

    public function setToAt(\DateTimeImmutable $toAt): static
    {
        $this->toAt = $toAt;

        return $this;
    }

    public function getBank(): ?Bank
    {
        return $this->bank;
    }

    public function setBank(?Bank $bank): static
    {
        $this->bank = $bank;

        return $this;
    }

    public function getProperty(): ?Property
    {
        return $this->property;
    }

    public function setProperty(?Property $property): static
    {
        $this->property = $property;

        return $this;
    }

    public function getBillingPeriod(): ?MortgageBillingPeriodEnum
    {
        return $this->billingPeriod;
    }

    public function setBillingPeriod(MortgageBillingPeriodEnum $billingPeriod): static
    {
        $this->billingPeriod = $billingPeriod;

        return $this;
    }

    public function getMortgageType(): ?MortgageTypeEnum
    {
        return $this->mortgageType;
    }

    public function setMortgageType(MortgageTypeEnum $mortgageType): static
    {
        $this->mortgageType = $mortgageType;

        return $this;
    }

    public function getRate(): ?string
    {
        return $this->rate;
    }

    public function setRate(string $rate): static
    {
        $this->rate = $rate;

        return $this;
    }

    /**
     * @return Collection<int, FinancialEntry>
     */
    public function getFinancialEntries(): Collection
    {
        return $this->financialEntries;
    }

    public function addFinancialEntry(FinancialEntry $financialEntry): static
    {
        if (!$this->financialEntries->contains($financialEntry)) {
            $this->financialEntries->add($financialEntry);
            $financialEntry->setMortgage($this);
        }

        return $this;
    }

    public function removeFinancialEntry(FinancialEntry $financialEntry): static
    {
        if ($this->financialEntries->removeElement($financialEntry)) {
            // set the owning side to null (unless already changed)
            if ($financialEntry->getMortgage() === $this) {
                $financialEntry->setMortgage(null);
            }
        }

        return $this;
    }

    public function getAmount(): ?string
    {
        return $this->amount;
    }

    public function setAmount(?string $amount): static
    {
        $this->amount = $amount;

        return $this;
    }

    public function getAmortizationPercent(): ?string
    {
        return $this->amortizationPercent;
    }

    public function setAmortizationPercent(?string $amortizationPercent): static
    {
        $this->amortizationPercent = $amortizationPercent;

        return $this;
    }

    public function getAmortizationType(): ?MortgageAmortizationTypeEnum
    {
        return $this->amortizationType;
    }

    public function setAmortizationType(?MortgageAmortizationTypeEnum $amortizationType): static
    {
        $this->amortizationType = $amortizationType;

        return $this;
    }

    public function getAmortizationAmount(): ?string
    {
        return $this->amortizationAmount;
    }

    public function setAmortizationAmount(?string $amortizationAmount): static
    {
        $this->amortizationAmount = $amortizationAmount;

        return $this;
    }
}

src/Form/TenantType.php
<?php

namespace App\Form;

use App\Entity\Tenant;
use App\Entity\Property;
use App\Enum\AccessRoleEnum;
use App\Repository\PropertyRepository;
use Symfony\Component\Form\AbstractType;
use Symfony\Bundle\SecurityBundle\Security;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;

class TenantType extends AbstractType
{
    private Security $security;

    public function __construct(Security $security)
    {
        $this->security = $security;
    }
    
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('firstname', TextType::class, [
                'label' => 'Prénom'
            ])
            ->add('lastname', TextType::class, [
                'label' => 'Nom'
            ])
            ->add('email', EmailType::class, [
                'label' => 'Adresse email',
                'required' => false
            ])
            ->add('phoneNumber', TextType::class, [
                'label' => 'Téléphone',
                'required' => false

            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Tenant::class,
        ]);
    }
}

src/Controller/TenantController.php
<?php

namespace App\Controller;

use App\Entity\Tenant;
use App\Entity\Property;
use App\Form\TenantType;
use App\Enum\AccessRoleEnum;
use App\Service\PropertyService;
use App\Service\AccessControlService;
use App\Repository\PropertyRepository;
use App\Repository\UploadFileRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;
use Symfony\Component\Routing\Requirement\Requirement;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;

#[Route('/tenant')]
final class TenantController extends AbstractController
{
    private AccessControlService $accessControlService;

    public function __construct(AccessControlService $accessControlService)
    {
        $this->accessControlService = $accessControlService;
    }
    
    #[Route(name: 'app_tenant_index', methods: ['GET'])]
    public function index(PropertyRepository $propertyRepository, UploadFileRepository $uploadFileRepository, EntityManagerInterface $entityManager): Response
    {
        $properties = $propertyRepository->findAccessibleProperties($this->getUser(), [AccessRoleEnum::MEMBER, AccessRoleEnum::OWNER]);

        //on récupère les locataires liés aux propriétés
        $tenants = $entityManager->createQuery("
            SELECT t FROM App\Entity\Tenant t
            JOIN t.lease l
            JOIN l.property p
            WHERE p IN (:properties)
        ")
        ->setParameter('properties', $properties)
        ->getResult();

        //on cherche l'image liée à la propriété pour afficher dans le card header
        $images = [];
        foreach ($tenants as $tenant) {
            $property = $tenant->getLease()->getProperty();
            $uploadsImages = $uploadFileRepository->findOneBy(['property' => $property->getId(), 'type' => 'image']);
                if (!empty($uploadsImages)) { //on récupère la première immage
                    $images[$tenant->getId()] = $uploadsImages;
                }
            }

        return $this->render('tenant/index.html.twig', [
            'tenants' => $tenants,
            'images' => $images
        ]);
    }

    #[Route('/new', name: 'app_tenant_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager, PropertyService $propertyService): Response
    {
        $tenant = new Tenant();
        $form = $this->createForm(TenantType::class, $tenant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //check que la date d'entrée ne correspond pas à une date déjà louée
            if($propertyService->haveTenantBetweenTwoDates($tenant->getProperty(), $tenant->getRentalStartDate(), $tenant->getRentalEndDate()))
            {
                $this->addFlash('warning', 'Date de location ce chevauche avec les locations en cours. Veuillez choisir une autre date de location.');
                return $this->redirectToRoute('app_tenant_new', [$tenant], Response::HTTP_SEE_OTHER);
            }

            $entityManager->persist($tenant);
            $entityManager->flush();

            $this->addFlash('success','Le locataire a bien été crée');

            return $this->redirectToRoute('app_tenant_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('tenant/new.html.twig', [
            'tenant' => $tenant,
            'form' => $form,
            'properties' => $entityManager->getRepository(Property::class)->findAccessibleProperties($this->getUser(), [AccessRoleEnum::MEMBER, AccessRoleEnum::OWNER]),
        ]);
    }

    #[Route('/{id}', name: 'app_tenant_show', methods: ['GET'], requirements: ['id' => Requirement::POSITIVE_INT])]
    public function show(Tenant $tenant): Response
    {
        $propertyCheck = $this->accessControlService->canAccessProperty($this->getUser(), $tenant->getProperty(), AccessRoleEnum::MEMBER);
        if (!$propertyCheck) {
            throw $this->createAccessDeniedException('Vous n’avez pas accès à ces informations.');
        }

        return $this->render('tenant/show.html.twig', [
            'tenant' => $tenant,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_tenant_edit', methods: ['GET', 'POST'], requirements: ['id' => Requirement::POSITIVE_INT])]
    public function edit(Request $request, Tenant $tenant, EntityManagerInterface $entityManager, PropertyService $propertyService): Response
    {
        $propertyCheck = $this->accessControlService->canAccessProperty($this->getUser(), $tenant->getProperty(), AccessRoleEnum::MEMBER);
        if (!$propertyCheck) {
            throw $this->createAccessDeniedException('Vous n’avez pas accès à ces informations.');
        }

        $form = $this->createForm(TenantType::class, $tenant);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            //check que la date d'entrée ne correspond pas à une date déjà louée
            if($propertyService->haveTenantBetweenTwoDates($tenant->getProperty(), $tenant->getRentalStartDate(), $tenant->getRentalEndDate()))
            {
                $this->addFlash('warning', 'Date de location ce chevauche avec les locations en cours. Veuillez choisir une autre date de location.');
                return $this->redirectToRoute('app_tenant_index', [$tenant], Response::HTTP_SEE_OTHER);
            }
            
            $entityManager->flush();

            $this->addFlash('success','Modification effectuée');

            return $this->redirectToRoute('app_tenant_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('tenant/edit.html.twig', [
            'tenant' => $tenant,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_tenant_delete', methods: ['POST'], requirements: ['id' => Requirement::POSITIVE_INT])]
    public function delete(Request $request, Tenant $tenant, EntityManagerInterface $entityManager): Response
    {
        $propertyCheck = $this->accessControlService->canAccessProperty($this->getUser(), $tenant->getProperty(), AccessRoleEnum::MEMBER);
        if (!$propertyCheck) {
            throw $this->createAccessDeniedException('Vous n’avez pas accès à ces informations.');
        }

        if ($this->isCsrfTokenValid('delete'.$tenant->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($tenant);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_tenant_index', [], Response::HTTP_SEE_OTHER);
    }

    /**
     * Route permettant de renouveler la location d'un locataire
     */
    #[Route('/{id}/lease/renew', name: 'app_tenant_lease_renew', methods: ['GET'], requirements: ['id' => Requirement::POSITIVE_INT])]
    public function leaseRenew(Request $request, Tenant $tenant, EntityManagerInterface $entityManager): Response
    {
        $propertyCheck = $this->accessControlService->canAccessProperty($this->getUser(), $tenant->getProperty(), AccessRoleEnum::MEMBER);
        if (!$propertyCheck) {
            throw $this->createAccessDeniedException('Vous n’avez pas accès à ces modifications.');
        }

        $rentTo = $tenant->getRentalEndDate();
        if($rentTo < new \DateTimeImmutable()) {
            //on ajoute 1 an à la date de fin du bail
            $newDate = (new \DateTimeImmutable(date('Y/m/d', $tenant->getRentalEndDate()->getTimestamp())))->modify('+1 year');
            $tenant->setRentalEndDate($newDate);
            $this->addFlash('success', 'La durée du bail a été renouvelée');

            //on boucle pour récupérer tous les types de loyer / charges et modifier la date de fin
            foreach ($tenant->getPropertyRents() as $key => $value) {
                if($value->getEndedAt() < $tenant->getRentalEndDate()) {
                    $value->setEndedAt($tenant->getRentalEndDate());
                }
            }
        }else{
            $this->addFlash('warning', 'Aucun bail à renouveler');
            return $this->redirectToRoute('app_tenant_index', [], Response::HTTP_SEE_OTHER);
        }

        $entityManager->flush();
        $this->addFlash('success', 'Les loyers on été renouvelé pour 1 an');
        return $this->redirectToRoute('app_tenant_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/tenant/_delete_form.html.twig
<form method="post" action="{{ path('app_tenant_delete', {'id': tenant.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ tenant.id) }}">
    <button class="btn">Delete</button>
</form>

templates/tenant/_form.html.twig
{% import 'form_macros.html.twig' as macros %}
{{ form_start(form, {'attr': {'class': 'space-y-6'}}) }}

<div class="md:grid md:grid-cols md:gap-4">

    {{ macros.field(form.lastname, 'Nom', '') }}
    {{ macros.field(form.firstname, 'Prénom', '') }}
    {{ macros.field(form.email, 'Email', '') }}
    {{ macros.field(form.phoneNumber, 'Numéro de téléphone', '') }}

    <div class="relative flex py-5 items-center col-span-2">
    <div class="flex-grow border-t border-gray-400"></div>
    <span class="flex-shrink mx-4 text-gray-400">Info appartement</span>
    <div class="flex-grow border-t border-gray-400"></div>
    </div>

    {{ macros.field(form.rentalStartDate, 'Date d\'entrée', '') }}
    {{ macros.field(form.rentalEndDate, 'Fin de bail', '') }}

    <div class="md:col-span-2">
        {{ form_label(form.property, 'Appartement', {'label_attr': {'class': 'block text-sm font-medium text-gray-700'}}) }}
        {{ form_widget(form.property, {'attr': {'class': 'input-base', 'onchange': 'addTenant(this.value)'}})  }}
    </div>
    
</div>
    <div id="tenant" class="col-span-2 text-sm font-medium text-gray-700 place-items-center spinner">
    </div>

<div>
    <button class="mt-4 py-2 px-4 bg-blue-600 text-white font-bold rounded hover:bg-blue-700">
        {{ button_label|default('Enregistrer') }}
    </button>
    <button onclick="history.back()" class="mt-4 py-2 px-4 bg-red-600 text-white font-bold rounded hover:bg-red-700">Annuler</button>
</div>

{{ form_end(form) }}

templates/tenant/edit.html.twig
{% extends 'base.html.twig' %}

{% set pageName = "Modifier locataire" %}
{% block title %}{{pageName}}{% endblock %}
{% block pageName %}{{pageName}}{% endblock %}

{% block body %}
    <div class="flex items-center justify-center min-h-screen bg-gray-100">
        <div class="w-full max-w-2xl p-6 bg-white rounded-lg shadow-lg">
            <h1 class="text-2xl font-semibold text-center text-gray-800 mb-5">{{pageName}}</h1>

            <div class="bg-gray-50 p-4 rounded-md mb-6">
                <p class="text-gray-600"></p>
            </div>

            {{ include('tenant/_form.html.twig') }}

        </div>
    </div>
{% endblock %}

{% block javascripts %}
<script>

document.addEventListener("DOMContentLoaded", () => {

    const nameRegex = /^([A-Z]|[0-9]+)[-a-zA-ZÀ-ú\s]{2,100}$/;
    const descriptionRegex = /^[-a-zA-ZÀ-ú\s]{5,255}$/;
    const emailRegex = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
    const swissPhoneRegex = /^(\b(0041|0)|\B\+41)(\s?\(0\))?(\s)?[1-9]{2}(\s)?[0-9]{3}(\s)?[0-9]{2}(\s)?[0-9]{2}\b$/;

    validateInput('tenant_lastname', nameRegex)
    validateInput('tenant_firstname', nameRegex)
    validateInput('tenant_email', emailRegex, false)
    validateInput('tenant_phoneNumber', swissPhoneRegex, false)


});
</script>

<script>
window.addEventListener("load", () => {
    document.getElementById("menu_btn_tenant").classList.add("menu-btn-active");
})
</script>
{% endblock %}

templates/tenant/index.html.twig
{% extends 'base.html.twig' %}

{% set pageName = "Liste des locataires" %}
{% block title %}{{pageName}}{% endblock %}
{% block pageName %}{{pageName}}{% endblock %}

{% block body %}
    <div class="container mx-auto p-4">
        <h1 class="text-2xl font-bold mb-6 text-center md:hidden">{{pageName}}</h1>
            <div class="my-4 flex justify-center">
                <a href="{{ path('app_tenant_new') }}" class="inline-block btn-blue-to-emrald">Ajouter un locataire</a>
            </div>
        <div class="grid grid-cols-1 md:grid-cols-2 flex items-start lg:grid-cols-3 gap-6">
            {% for tenant in tenants %}
                <div class="bg-white shadow-md rounded-lg overflow-hidden border-4 border-white hover:shadow-xl">

            {% if images[tenant.id] is defined %}
                {% set path = asset('uploads/' ~ tenant.lease.property.id ~ '/' ~ images[tenant.id].fileName) %}
            {% else %}
                {% set path = asset('media/app_default.JPE') %}
            {% endif %}
                <div class="relative">
                    <img src="{{ path }}" class="w-full h-48 object-cover opacity-50">
                    <div class="absolute inset-0 bg-black/50 flex flex-col items-start justify-center px-4">
                        <!-- Nom et prénom -->
                        {% set color = 'gray' %}
                        {# si les dates de bail sont passées, on met la couleur rouge (les locataires n'ont plus de bails actif) #}
                        {% if tenant.lease.toAt|date("U") <= "now"|date("U") %}{% set color = 'red' %}{% endif %}
                        
                        <h2 class="text-white text-xl font-semibold bg-{{color}}-900 px-4 py-2 w-fit">
                            {{ tenant.firstname }} {{ tenant.lastname }}
                        </h2>

                        <!-- Email -->
                        <span class="mt-1 bg-blue-200 text-blue-800 text-sm font-semibold px-2.5 py-0.5 rounded">
                            {{ tenant.email }}
                        </span>
                    </div>
                </div>
                    <hr class="m-2">
                    <div class="bg-white p-4">
                        <ul>
                            <li><strong>Numéro de téléphone:</strong> {{ tenant.phonenumber }}</li>
                            <li><strong>Date d'entrée:</strong> {{ tenant.lease.fromAt|format_datetime(locale='fr',pattern="dd MMMM YYYY") }}</li>
                            <li><strong>Fin de bail:</strong> {{ tenant.lease.toAt|format_datetime(locale='fr',pattern="dd MMMM YYYY") }}</li>
                        </ul>
                    </div>
                    <hr class="m-2">

                    <div class="p-4 flex justify-center bg-white gap-4">
                        <a href="{{ path('app_tenant_show', {'id': tenant.id}) }}" class="inline-flex items-center border-[1px] border-blue-500 text-blue-500 font-semibold py-1 px-4 rounded hover:bg-blue-300 transition-colors"><span class="material-symbols-outlined text-sm">visibility</span>&nbsp;Voir</a>
                        {% if tenant.lease.toAt|date("U") <= "now"|date("U") %}                        
                            <a href="{{ path('app_tenant_lease_renew', {'id': tenant.id}) }}" class="inline-flex items-center border-[1px] border-orange-500 text-orange-500 font-semibold py-1 px-4 rounded hover:bg-orange-300 transition-colors">Renouveller le bail</a>
                        {% endif %}
                        <a href="{{ path('app_tenant_edit', {'id': tenant.id}) }}" class="inline-flex items-center border-[1px] border-lime-500 text-lime-500 font-semibold py-1 px-4 rounded hover:bg-lime-300 transition-colors"><span class="material-symbols-outlined text-sm">edit</span>&nbsp;Modifier</a>
                    </div>
                </div>
            {% else %}
                <div class="col-span-full text-center text-gray-600">
                        <div class="my-2 flex justify-center bg-amber-500 px-5 my-4 rounded-lg">
                            Aucun locataire actuelleemnt.
                        </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

{% block javascripts %}
<script>
window.addEventListener("load", () => {
    document.getElementById("menu_btn_tenant").classList.add("menu-btn-active");
})
</script>
{% endblock %}

templates/tenant/new.html.twig
{% extends 'base.html.twig' %}

{% set pageName = "Nouveau locataire" %}
{% block title %}{{pageName}}{% endblock %}
{% block pageName %}{{pageName}}{% endblock %}

{% block body %}
    <div class="flex items-center justify-center min-h-screen bg-gray-100">
        <div class="w-full max-w-2xl p-6 bg-white rounded-lg shadow-lg">
            <h1 class="text-2xl font-semibold text-center text-gray-800 mb-5">{{ pageName }}</h1>

{% if properties is not empty %}
            <div class="bg-gray-50 p-4 rounded-md mb-6">
                <p class="text-gray-600">Veuillez remplir les informations ci-dessous :</p>
            </div>

    {{ include('tenant/_form.html.twig') }}
{% else %}
    <div class="my-2 flex justify-center bg-amber-500 px-5 my-4 rounded-lg">
        Vous devez ajoutez une propriété avant de pouvoir ajouter un locataire.
    </div>
{% endif %}
            

        </div>
    </div>
{% endblock %}

{% block javascripts %}
<script>

document.addEventListener("DOMContentLoaded", () => {

    const nameRegex = /^([A-Z]|[0-9]+)[-a-zA-ZÀ-ú\s]{2,100}$/;
    const descriptionRegex = /^[-a-zA-ZÀ-ú\s]{5,255}$/;
    const emailRegex = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
    const swissPhoneRegex = /^(\b(0041|0)|\B\+41)(\s?\(0\))?(\s)?[1-9]{2}(\s)?[0-9]{3}(\s)?[0-9]{2}(\s)?[0-9]{2}\b$/;

    validateInput('tenant_lastname', nameRegex)
    validateInput('tenant_firstname', nameRegex)
    validateInput('tenant_email', emailRegex, false)
    validateInput('tenant_phoneNumber', swissPhoneRegex, false)
});

document.addEventListener("DOMContentLoaded", function () {
    let startDateInput = document.getElementById("tenant_rentalStartDate");
    let endDateInput = document.getElementById("tenant_rentalEndDate");

    function getFirstDayOfNextMonth() {
        let today = new Date();
        return new Date(today.getFullYear(), today.getMonth() + 1, 2);
    }

    function updateEndDate() {
        if (startDateInput.value) {
            let startDate = new Date(startDateInput.value);
            startDate.setFullYear(startDate.getFullYear() + 1);
            startDate.setDate(startDate.getDate() - 1); // Soustrait un jour
            endDateInput.value = startDate.toISOString().split('T')[0];
        }
    }

    // Définir automatiquement la date de début au premier jour du mois suivant
    let firstDayNextMonth = getFirstDayOfNextMonth();
    startDateInput.value = firstDayNextMonth.toISOString().split('T')[0];

    // Mettre à jour la date de fin automatiquement
    updateEndDate();

    startDateInput.addEventListener("change", updateEndDate);
});

addEventListener("load", (event) => {

    addTenant(document.getElementById('tenant_property').value);
});
</script>

<script>
window.addEventListener("load", () => {
    document.getElementById("menu_btn_tenant").classList.add("menu-btn-active");
})
</script>
{% endblock %}